<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>schema.rb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)^
	    (\s*+
	        (module|class|def
	        |unless|if
	        |case
	        |begin
	        |for|while|until
			 |^=begin
	        |(  "(\\.|[^"])*+"          # eat a double quoted string
	         | '(\\.|[^'])*+'        # eat a single quoted string
	         |   [^#"']                # eat all but comments and strings
	         )*
	         (                        \s   (do|begin|case)
	         | (?&lt;!\$)[-+=&amp;|*/~%^&lt;&gt;~] \s*+ (if|unless)
	         )
	        )\b
	        (?! [^;]*+ ; .*? \bend\b )
	    |(  "(\\.|[^"])*+"              # eat a double quoted string
	     | '(\\.|[^'])*+'            # eat a single quoted string
	     |   [^#"']                    # eat all but comments and strings
	     )*
	     ( \{ (?!  [^}]*+ \} )
	     | \[ (?! [^\]]*+ \] )
	     )
	    ).*$
	|   [#] .*? \(fold\) \s*+ $         # Sune’s special marker
	</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(   (^|;) \s*+ end   \s*+ ([#].*)? $
		|   (^|;) \s*+ end \. .* $
		|   ^     \s*+ [}\]] \s*+ ([#].*)? $
		|   [#] .*? \(end\) \s*+ $    # Sune’s special marker
		|   ^=end
		)</string>
	<key>name</key>
	<string>Ruby ActiveRecord Schema</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(add_index)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rails</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.activerecord.schema.add-index</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(create_table)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rails</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(do).*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start-block.ruby.rspec</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.activerecord.schema.create-table</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.rails.schema</string>
	<key>uuid</key>
	<string>1676D27A-49ED-416E-8EC2-E2892FF4AC21</string>
</dict>
</plist>
